version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@pixi/app"
    versions:
    - 5.3.7
    - 5.3.8
    - 6.0.1
  - dependency-name: "@pixi/display"
    versions:
    - 5.3.7
    - 5.3.8
    - 6.0.1
  - dependency-name: "@pixi/core"
    versions:
    - 5.3.7
    - 5.3.8
    - 6.0.1
  - dependency-name: svelte
    versions:
    - 3.31.0
    - 3.32.1
    - 3.32.3
    - 3.34.0
  - dependency-name: "@pixi/ticker"
    versions:
    - 5.3.7
    - 5.3.8
  - dependency-name: rollup
    versions:
    - 2.35.1
    - 2.38.1
    - 2.38.3
    - 2.39.0
    - 2.40.0
  - dependency-name: svelte-preprocess
    versions:
    - 4.6.5
    - 4.6.9
  - dependency-name: svelte-check
    versions:
    - 1.1.24
    - 1.1.36
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.0.1
  - dependency-name: rollup-plugin-svelte
    versions:
    - 7.0.0
